name: todo
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  time_pickerr: ^1.0.6



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  hive_generator: ^2.0.1


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
   - images/
   - assets/

  fonts:
    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf


